spring.application.name=gestion-stages

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_stages
spring.datasource.username=postgres
spring.datasource.password=molka
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:uneCleSecreteTresLonguePourSignerLesTokensJWTGestionStagesLaPoste2026}
jwt.expiration=86400000
server.port=8081

# File Storage
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sadkaouimolka3@gmail.com
spring.mail.password=krdu hjmr xrcw ejgh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true